# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openedprojects', '0002_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedprojects.Post')),
            ],
        ),
    ]
